<h2 class="first right_section_title">Links</h2>

<table width="100%" cellpadding="0" cellspacing="10">

<td><a href="http://www.1000genomes.org"><img src="/i/species/48/Homo_sapiens.png" alt="" style="border:1px solid #99c;" /></a></td>
<td width="90%">
  <a href="http://www.1000genomes.org"><b>1000 Genomes</b></a> &rarr;<br />
More information about the 1000 Genomes Project on the 1000 genomes
  main site.
</td>
</tr>

<td><a href="http://phase1browser.1000genomes.org"><img src="/i/species/48/Homo_sapiens.png" alt="" style="border:1px solid #99c;" /></a></td>
<td width="90%">
  <a href="http://phase1browser.1000genomes.org"><b>Phase1 browser</b></a> &rarr;<br />
This browser is based on Ensembl release 73 and represents the variant set analysed as part of <a href="http://www.nature.com/nature/journal/v491/n7422/full/nature11632.html">An integrated map of genetic variation from 1,092 human genomes</a> , Nature 491, 56-65.
</td>
</tr>

<td><a href="ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/browser/1000genomes_browser_main_project_20101123/20111013_ensembl_browser_63.doc" target="_blank"><img src="/i/species/48/Homo_sapiens.png" alt="" style="border:1px solid #99c;" /></a></td>
<td width="90%">
  <a href="ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/browser/1000genomes_browser_main_project_20110521/The_1000_Genomes_Browser_Tutorial.ensembl_65.doc" target="_blank"><b>Tutorial</b></a> &rarr;<br />
  The 1000 Genomes Browser Tutorial.
</td>
</tr>

</table>






