<h1 class="first section_title ">The 1000 Genomes Browser</h1>



            <h2> 1000 Genomes Mirror of <a href="http://Sep2013.archive.ensembl.org">Ensembl v73</a> </h2>
<p>
The Ensembl v73 databases contain the majority of the <a href="http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1/analysis_results">1000 genomes phase1 variants</a>. This browser represents a direct mirror of the Ensembl 73 databases which includes all the 1000 genomes variants in dbSNP and the 1000 genomes
structural variants in the DGVa. We have also added accessibility tracks based on our <a href="http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1/analysis_results/supporting/accessible_genome_masks/">accessible genome mask files</a>. </p>
<p>
If you wish to view newer data you can view vcf files on the browser using our <a href="/info/website/upload/large.html">adding custom tracks menu</a>. 
</p>

<!--
<h2>Ensembl-based browser provides early access to 1000genomes data </h2>
<p>In order to facilitate immediate analysis of the 1000 Genomes Project data by the whole scientific community, this browser (based on Ensembl) integrates the SNP and INDEL calls from the <a href="ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20110521/">phase 1 integrated release</a>. This data has be submitted to dbSNP, and once rsid's have been allocated, will be absorbed into the UCSC and Ensembl browsers according to their respective release cycles. Until that point <b>any non rs SNP id's on this site are temporary and will NOT be maintained</b>.</p>
-->

<p><a href="/ssi/features.html">Read more about this browser's features.</a></p>

