<h1 class="first section_title ">The 1000 Genomes Browser</h1>
<h2> 1000 Genomes Browser based on <a href="http://grch37.ensembl.org">Ensembl v76 GRCh37</a> </h2>
<p>
As the Phase 3 1000 Genomes variants have not yet made it to dbSNP or the DGVa, we have created a version of the Ensembl databases which contain the phase3 autosomal variants. This is presented here alongside the v76 GRCh37 Ensembl core and regulatory databases. This release represents more than 80M short variants with genotypes for 2504 individuals across 26 populations.
</p>
<p><a href="/ssi/features.html">Read more about this browser's features.</a></p>

