<span>
<p>The 1000 Genomes Project is an international collaborative project described
at <a href="http://www.1000genomes.org">www.1000genomes.org.</a> </p>
<p>The 1000 Genomes Browser is based on Ensembl web code. </p>
<p><a href="http://www.ensembl.org">Ensembl</a> is a joint project of <span id="ebi_logo"> <a href="http://www.ebi.ac.uk/"> 
<img src="/img/ebi_logo.png" alt="EMBL-EBI" title="European BioInformatics Institute" style="width: 100px; height: 31px;"  align="absmiddle"></a></span>
and the <a href ="http://www.sanger.ac.uk">Wellcome Trust Sanger Institute</a>
<a href="http://www.sanger.ac.uk" >   
<img src="/img/wtsi_rev.png" style="height: 25px; " align="absmiddle" alt="Sanger" title="Wellcome Trust Sanger Institute" />
</a>
</span>
		  
