<div class="white boxed">
<h1 class="first section_title">Browser update October 2014</h1>
<h2>This release is based on <a href="http://grch37.ensembl.org">Ensembl 76</a> and contains the phase 3 integrated release for 2054 individuals. The data can be found on <a href="ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/" target="_blank">the ftp site</a>.</h2>
<h2>Please see <a href="http://www.1000genomes.org">www.1000genomes.org</a> for more information about the data presented here and instructions for downloading the complete data set.</h2>
<ul>
<li> <a href="/Homo_sapiens/Location/View?r=6:133098746-133108745">View sample data</a> </li>
</ul>
</div>