<h1 class="first section_title">Start Browsing 1000 Genomes data</h1>

<table width="100%" cellpadding="0" cellspacing="10">
<tr>
<td><a href="/Homo_sapiens"><img src="/i/species/48/Homo_sapiens.png" alt="" style="border:1px solid #99c;" /></a></td>
<td width="90%">
  <a href="/Homo_sapiens"><b>Browse Human</b></a> &rarr;<br />
GRCh37
</td>
</tr>

<tr>
<td></td>
<td width="90%">
  <a href="/Homo_sapiens/Transcript/ProtVariations?g=ENSG00000128573;r=7:114055378-114330012;t=ENST00000393489
"><b>Protein variations</b></a> &rarr;<br />
View the consequences of sequence variation at the level of each protein in the genome.
</td>
</tr>


<tr>
<td></td>
<td width="90%">
  <a href="/Homo_sapiens/Variation/Individual?r=6:74125388-74126388;v=rs311685;vdb=variation;vf=29731040"><b>Individual genotypes</b></a> &rarr;<br />
Show different individual's genotype, for a variant.
</td>
</tr>

</table>




